import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";

export const generatePersonalPDF = (
  userName: string,
  monthYear: string,
  attendance: any[],
  payments: any[],
  earned: number,
  paid: number,
  balance: number,
  workDays: number,
  dailyWage: number
) => {
  const doc = new jsPDF("p", "mm", "a4");

  // Colors
  const primaryColor = [30, 64, 175]; // #1E40AF

  // Header
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 210, 40, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont("helvetica", "bold");
  doc.text("WorkDay Pro", 14, 20);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Monthly Work Report: ${monthYear}`, 14, 28);

  doc.setFontSize(10);
  doc.text(`User: ${userName}`, 14, 34);

  // Summary Stats
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  doc.text("Summary", 14, 50);

  autoTable(doc, {
    startY: 55,
    head: [['Work Days', 'Daily Wage', 'Total Earned', 'Total Received', 'Balance']],
    body: [[
      workDays.toString(),
      `Rs. ${dailyWage}`,
      `Rs. ${earned}`,
      `Rs. ${paid}`,
      `Rs. ${balance}`
    ]],
    theme: 'grid',
    headStyles: { fillColor: primaryColor as [number, number, number], textColor: [255, 255, 255] },
    styles: { fontSize: 10, halign: 'center' },
  });

  // Attendance Table
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  // @ts-ignore
  doc.text("Attendance Records", 14, doc.lastAutoTable.finalY + 15);

  const attBody = attendance.map(a => [
    a.date,
    a.status,
    `Rs. ${a.dailyWage}`
  ]);

  autoTable(doc, {
    // @ts-ignore
    startY: doc.lastAutoTable.finalY + 20,
    head: [['Date', 'Status', 'Daily Wage']],
    body: attBody,
    theme: 'grid',
    headStyles: { fillColor: [100, 116, 139], textColor: [255, 255, 255] },
    styles: { fontSize: 9 },
  });

  // Payments Table
  doc.setFontSize(14);
  doc.setFont("helvetica", "bold");
  // @ts-ignore
  doc.text("Payment Records", 14, doc.lastAutoTable.finalY + 15);

  const payBody = payments.map(p => [
    p.date,
    p.type,
    `Rs. ${p.amount}`,
    p.note || '-'
  ]);

  autoTable(doc, {
    // @ts-ignore
    startY: doc.lastAutoTable.finalY + 20,
    head: [['Date', 'Type', 'Amount', 'Note']],
    body: payBody,
    theme: 'grid',
    headStyles: { fillColor: [100, 116, 139], textColor: [255, 255, 255] },
    styles: { fontSize: 9 },
  });

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by WorkDay Pro - Page ${i} of ${pageCount}`, 14, 290);
  }

  doc.save(`WorkDay_Report_${monthYear}.pdf`);
};

export const generateContractorPDF = (
  contractorName: string,
  monthYear: string,
  workersData: any[]
) => {
  const doc = new jsPDF("l", "mm", "a4");

  const primaryColor = [30, 64, 175]; // #1E40AF

  // Header
  doc.setFillColor(primaryColor[0], primaryColor[1], primaryColor[2]);
  doc.rect(0, 0, 297, 30, "F");

  doc.setTextColor(255, 255, 255);
  doc.setFontSize(20);
  doc.setFont("helvetica", "bold");
  doc.text("WorkDay Pro", 14, 15);

  doc.setFontSize(12);
  doc.setFont("helvetica", "normal");
  doc.text(`Contractor: ${contractorName} | Month: ${monthYear}`, 14, 23);

  // Table
  const body = workersData.map((w, i) => [
    i + 1,
    w.name,
    w.role,
    `Rs. ${w.wage}`,
    w.present,
    w.absent,
    w.half,
    w.worked,
    `Rs. ${w.earned}`,
    `Rs. ${w.paid}`,
    `Rs. ${w.balance}`
  ]);

  autoTable(doc, {
    startY: 40,
    head: [['Sr', 'Name', 'Role', 'Wage', 'Present', 'Absent', 'Half', 'Worked', 'Earned', 'Paid/Adv', 'Balance']],
    body: body,
    theme: 'grid',
    headStyles: { fillColor: primaryColor as [number, number, number], textColor: [255, 255, 255] },
    styles: { fontSize: 9 },
    columnStyles: {
      0: { cellWidth: 10 },
      8: { fontStyle: 'bold' },
      10: { fontStyle: 'bold', textColor: [30, 64, 175] }
    }
  });

  // Footer
  const pageCount = doc.internal.pages.length - 1;
  for(let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150);
    doc.text(`Generated by WorkDay Pro - Page ${i} of ${pageCount}`, 14, 200);
  }

  doc.save(`Contractor_Report_${contractorName}_${monthYear}.pdf`);
};
