import { createContext, useContext, useState, useEffect, ReactNode } from "react";

const locales: Record<string, Record<string, string>> = {
  en: {
    appName: "WorkDay",
    markAttendance: "Mark Attendance",
    marked: "Attendance Marked ✓",
    totalDays: "Days Worked",
    earnings: "Estimated Earnings",
    thisMonth: "This Month",
    dashboard: "Home",
    history: "History",
    settings: "Settings",
    calendar: "Calendar",
    present: "Present",
    absent: "Absent",
    date: "Date",
    status: "Status",
    dailyWage: "Daily Wage",
    language: "Language",
    logout: "Logout",
    login: "Login",
    loginWith: "Sign in with Google",
    welcome: "Welcome",
    today: "Today",
    save: "Save",
    saved: "Saved!",
    noRecords: "No records yet",
    loginSubtitle: "Track your work, know your earnings",
  },
  hi: {
    appName: "वर्कडे",
    markAttendance: "हाज़िरी लगाएं",
    marked: "हाज़िरी लग गई ✓",
    totalDays: "काम के दिन",
    earnings: "अनुमानित कमाई",
    thisMonth: "इस महीने",
    dashboard: "होम",
    history: "इतिहास",
    settings: "सेटिंग्स",
    calendar: "कैलेंडर",
    present: "उपस्थित",
    absent: "अनुपस्थित",
    date: "तारीख",
    status: "स्थिति",
    dailyWage: "दैनिक मजदूरी",
    language: "भाषा",
    logout: "लॉग आउट",
    login: "लॉगिन",
    loginWith: "Google से लॉगिन करें",
    welcome: "स्वागत है",
    today: "आज",
    save: "सेव करें",
    saved: "सेव हो गया!",
    noRecords: "कोई रिकॉर्ड नहीं",
    loginSubtitle: "अपना काम ट्रैक करें, कमाई जानें",
  },
  bn: {
    appName: "ওয়ার্কডে",
    markAttendance: "উপস্থিতি দিন",
    marked: "উপস্থিতি দেওয়া হয়েছে ✓",
    totalDays: "কাজের দিন",
    earnings: "আনুমানিক আয়",
    thisMonth: "এই মাসে",
    dashboard: "হোম",
    history: "ইতিহাস",
    settings: "সেটিংস",
    calendar: "ক্যালেন্ডার",
    present: "উপস্থিত",
    absent: "অনুপস্থিত",
    date: "তারিখ",
    status: "অবস্থা",
    dailyWage: "দৈনিক মজুরি",
    language: "ভাষা",
    logout: "লগ আউট",
    login: "লগইন",
    loginWith: "Google দিয়ে লগইন",
    welcome: "স্বাগতম",
    today: "আজ",
    save: "সেভ",
    saved: "সেভ হয়েছে!",
    noRecords: "কোনো রেকর্ড নেই",
    loginSubtitle: "আপনার কাজ ট্র্যাক করুন, আয় জানুন",
  },
  pa: {
    appName: "ਵਰਕਡੇ",
    markAttendance: "ਹਾਜ਼ਰੀ ਲਗਾਓ",
    marked: "ਹਾਜ਼ਰੀ ਲੱਗ ਗਈ ✓",
    totalDays: "ਕੰਮ ਦੇ ਦਿਨ",
    earnings: "ਅੰਦਾਜ਼ਨ ਕਮਾਈ",
    thisMonth: "ਇਸ ਮਹੀਨੇ",
    dashboard: "ਹੋਮ",
    history: "ਇਤਿਹਾਸ",
    settings: "ਸੈਟਿੰਗਾਂ",
    calendar: "ਕੈਲੰਡਰ",
    present: "ਹਾਜ਼ਰ",
    absent: "ਗੈਰਹਾਜ਼ਰ",
    date: "ਤਾਰੀਖ",
    status: "ਸਥਿਤੀ",
    dailyWage: "ਰੋਜ਼ਾਨਾ ਮਜ਼ਦੂਰੀ",
    language: "ਭਾਸ਼ਾ",
    logout: "ਲੌਗ ਆਊਟ",
    login: "ਲੌਗਇਨ",
    loginWith: "Google ਨਾਲ ਲੌਗਇਨ",
    welcome: "ਜੀ ਆਇਆਂ ਨੂੰ",
    today: "ਅੱਜ",
    save: "ਸੇਵ",
    saved: "ਸੇਵ ਹੋ ਗਿਆ!",
    noRecords: "ਕੋਈ ਰਿਕਾਰਡ ਨਹੀਂ",
    loginSubtitle: "ਆਪਣਾ ਕੰਮ ਟਰੈਕ ਕਰੋ, ਕਮਾਈ ਜਾਣੋ",
  },
  mr: {
    appName: "वर्कडे",
    markAttendance: "हजेरी लावा",
    marked: "हजेरी लागली ✓",
    totalDays: "कामाचे दिवस",
    earnings: "अंदाजित कमाई",
    thisMonth: "या महिन्यात",
    dashboard: "होम",
    history: "इतिहास",
    settings: "सेटिंग्ज",
    calendar: "कॅलेंडर",
    present: "उपस्थित",
    absent: "अनुपस्थित",
    date: "तारीख",
    status: "स्थिती",
    dailyWage: "दैनिक मजुरी",
    language: "भाषा",
    logout: "लॉग आउट",
    login: "लॉगिन",
    loginWith: "Google ने लॉगिन करा",
    welcome: "स्वागत आहे",
    today: "आज",
    save: "सेव्ह करा",
    saved: "सेव्ह झाले!",
    noRecords: "कोणतेही रेकॉर्ड नाहीत",
    loginSubtitle: "तुमचे काम ट्रॅक करा, कमाई जाणा",
  },
  ta: {
    appName: "ஒர்க்டே",
    markAttendance: "வருகை பதிவு",
    marked: "வருகை பதிவாகியது ✓",
    totalDays: "வேலை நாட்கள்",
    earnings: "மதிப்பிட்ட வருமானம்",
    thisMonth: "இந்த மாதம்",
    dashboard: "முகப்பு",
    history: "வரலாறு",
    settings: "அமைப்புகள்",
    calendar: "நாட்காட்டி",
    present: "வந்தது",
    absent: "வரவில்லை",
    date: "தேதி",
    status: "நிலை",
    dailyWage: "தினசரி ஊதியம்",
    language: "மொழி",
    logout: "வெளியேறு",
    login: "உள்நுழை",
    loginWith: "Google மூலம் உள்நுழை",
    welcome: "வரவேற்கிறோம்",
    today: "இன்று",
    save: "சேமி",
    saved: "சேமிக்கப்பட்டது!",
    noRecords: "பதிவுகள் இல்லை",
    loginSubtitle: "உங்கள் வேலையை கண்காணியுங்கள்",
  },
  te: {
    appName: "వర్క్‌డే",
    markAttendance: "హాజరు వేయండి",
    marked: "హాజరు వేయబడింది ✓",
    totalDays: "పని దినాలు",
    earnings: "అంచనా ఆదాయం",
    thisMonth: "ఈ నెల",
    dashboard: "హోమ్",
    history: "చరిత్ర",
    settings: "సెట్టింగ్స్",
    calendar: "క్యాలెండర్",
    present: "హాజరు",
    absent: "గైర్హాజరు",
    date: "తేదీ",
    status: "స్థితి",
    dailyWage: "రోజువారీ వేతనం",
    language: "భాష",
    logout: "లాగ్ అవుట్",
    login: "లాగిన్",
    loginWith: "Google తో లాగిన్",
    welcome: "స్వాగతం",
    today: "ఈ రోజు",
    save: "సేవ్",
    saved: "సేవ్ అయింది!",
    noRecords: "రికార్డులు లేవు",
    loginSubtitle: "మీ పనిని ట్రాక్ చేయండి",
  },
  gu: {
    appName: "વર્કડે",
    markAttendance: "હાજરી આપો",
    marked: "હાજરી નોંધાઈ ✓",
    totalDays: "કામના દિવસો",
    earnings: "અંદાજિત કમાણી",
    thisMonth: "આ મહિને",
    dashboard: "હોમ",
    history: "ઇતિહાસ",
    settings: "સેટિંગ્સ",
    calendar: "કૅલેન્ડર",
    present: "હાજર",
    absent: "ગેરહાજર",
    date: "તારીખ",
    status: "સ્થિતિ",
    dailyWage: "દૈનિક વેતન",
    language: "ભાષા",
    logout: "લૉગ આઉટ",
    login: "લૉગિન",
    loginWith: "Google થી લૉગિન",
    welcome: "સ્વાગત છે",
    today: "આજે",
    save: "સેવ",
    saved: "સેવ થઈ ગયું!",
    noRecords: "કોઈ રેકોર્ડ નથી",
    loginSubtitle: "તમારું કામ ટ્રૅક કરો, કમાણી જાણો",
  },
  kn: {
    appName: "ವರ್ಕ್‌ಡೇ",
    markAttendance: "ಹಾಜರಿ ಹಾಕಿ",
    marked: "ಹಾಜರಿ ಹಾಕಲಾಗಿದೆ ✓",
    totalDays: "ಕೆಲಸದ ದಿನಗಳು",
    earnings: "ಅಂದಾಜು ಗಳಿಕೆ",
    thisMonth: "ಈ ತಿಂಗಳು",
    dashboard: "ಹೋಮ್",
    history: "ಇತಿಹಾಸ",
    settings: "ಸೆಟ್ಟಿಂಗ್ಸ್",
    calendar: "ಕ್ಯಾಲೆಂಡರ್",
    present: "ಹಾಜರು",
    absent: "ಗೈರು",
    date: "ದಿನಾಂಕ",
    status: "ಸ್ಥಿತಿ",
    dailyWage: "ದೈನಿಕ ಕೂಲಿ",
    language: "ಭಾಷೆ",
    logout: "ಲಾಗ್ ಔಟ್",
    login: "ಲಾಗಿನ್",
    loginWith: "Google ನಿಂದ ಲಾಗಿನ್",
    welcome: "ಸ್ವಾಗತ",
    today: "ಇಂದು",
    save: "ಉಳಿಸಿ",
    saved: "ಉಳಿಸಲಾಗಿದೆ!",
    noRecords: "ಯಾವುದೇ ದಾಖಲೆಗಳಿಲ್ಲ",
    loginSubtitle: "ನಿಮ್ಮ ಕೆಲಸ ಟ್ರ್ಯಾಕ್ ಮಾಡಿ",
  },
  ml: {
    appName: "വർക്ക്‌ഡേ",
    markAttendance: "ഹാജർ രേഖപ്പെടുത്തുക",
    marked: "ഹാജർ രേഖപ്പെടുത്തി ✓",
    totalDays: "പ്രവൃത്തി ദിവസങ്ങൾ",
    earnings: "കണക്കാക്കിയ വരുമാനം",
    thisMonth: "ഈ മാസം",
    dashboard: "ഹോം",
    history: "ചരിത്രം",
    settings: "ക്രമീകരണങ്ങൾ",
    calendar: "കലണ്ടർ",
    present: "ഹാജർ",
    absent: "അഭാവം",
    date: "തീയതി",
    status: "സ്ഥിതി",
    dailyWage: "ദിവസ വേതനം",
    language: "ഭാഷ",
    logout: "ലോഗ് ഔട്ട്",
    login: "ലോഗിൻ",
    loginWith: "Google ഉപയോഗിച്ച് ലോഗിൻ",
    welcome: "സ്വാഗതം",
    today: "ഇന്ന്",
    save: "സേവ്",
    saved: "സേവ് ചെയ്തു!",
    noRecords: "രേഖകളൊന്നുമില്ല",
    loginSubtitle: "നിങ്ങളുടെ ജോലി ട്രാക്ക് ചെയ്യുക",
  },
};

const LANGUAGE_NAMES: Record<string, string> = {
  en: "English",
  hi: "हिन्दी",
  bn: "বাংলা",
  pa: "ਪੰਜਾਬੀ",
  mr: "मराठी",
  ta: "தமிழ்",
  te: "తెలుగు",
  gu: "ગુજરાતી",
  kn: "ಕನ್ನಡ",
  ml: "മലയാളം",
};

interface LanguageContextType {
  lang: string;
  setLang: (l: string) => void;
  t: (key: string) => string;
  languages: typeof LANGUAGE_NAMES;
}

const LanguageContext = createContext<LanguageContextType | null>(null);

export const useLanguage = () => {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used within LanguageProvider");
  return ctx;
};

export const LanguageProvider = ({ children }: { children: ReactNode }) => {
  const [lang, setLangState] = useState(() => localStorage.getItem("lang") || "en");

  const setLang = (l: string) => {
    setLangState(l);
    localStorage.setItem("lang", l);
  };

  const t = (key: string) => locales[lang]?.[key] || locales.en[key] || key;

  return (
    <LanguageContext.Provider value={{ lang, setLang, t, languages: LANGUAGE_NAMES }}>
      {children}
    </LanguageContext.Provider>
  );
};
