package com.dailywork.attedance.utils

import android.content.Context
import android.graphics.Canvas
import android.graphics.Color
import android.graphics.Paint
import android.graphics.Typeface
import android.graphics.pdf.PdfDocument
import java.io.File
import java.io.FileOutputStream

data class PdfData(
    val title: String,
    val subtitle: String,
    val name: String,
    val userId: String,
    val role: String,
    val monthYearStr: String,
    val monthNumericStr: String, // e.g., "03"
    val yearNumericStr: String, // e.g., "2024"
    val contractorName: String,
    val dailyWage: Double,
    val totalManDays: Double,
    val grossEarned: Double,
    val advanceDeducted: Double,
    val netPayable: Double,
    val logs: List<PdfLog>
)

data class PdfLog(
    val date: String,
    val status: String,
    val workType: String,
    val dailyWage: String,
    val overtime: String,
    val advanceAmount: String,
    val runningBalance: String
)

object PassbookPdfGenerator {

    private const val PAGE_WIDTH = 595 // A4 width at 72 PPI
    private const val PAGE_HEIGHT = 842 // A4 height at 72 PPI
    private const val MARGIN = 40f

    // Theme colors matching web jsPDF
    private val colorHeaderBg = Color.parseColor("#0f172a") // Deep blue/slate
    private val colorHeaderText = Color.WHITE
    private val colorHeaderSubText = Color.parseColor("#94a3b8")
    private val colorHeaderWorkerInfoText = Color.parseColor("#f8fafc")
    private val colorHeaderRoleInfoText = Color.parseColor("#cbd5e1")
    private val colorSummaryTitle = Color.parseColor("#0f172a")
    private val colorTableHeadBg1 = Color.parseColor("#1e40af")
    private val colorTableHeadBg2 = Color.parseColor("#64748b")
    private val colorPositive = Color.parseColor("#16a34a")
    private val colorNegative = Color.parseColor("#dc2626")
    private val colorStripedRow = Color.parseColor("#f8fafc")
    private val colorBorder = Color.parseColor("#e2e8f0")

    fun generatePdf(context: Context, data: PdfData): File? {
        val document = PdfDocument()
        var pageNumber = 1
        var yPos = 0f

        // Paints
        val paintHeaderBg = Paint().apply { color = colorHeaderBg; style = Paint.Style.FILL }
        val paintTextBold = Paint().apply { typeface = Typeface.create(Typeface.DEFAULT, Typeface.BOLD); isAntiAlias = true }
        val paintTextNormal = Paint().apply { typeface = Typeface.create(Typeface.DEFAULT, Typeface.NORMAL); isAntiAlias = true }
        val paintRectBorder = Paint().apply { color = colorBorder; style = Paint.Style.STROKE; strokeWidth = 1f }
        val paintRectFill = Paint().apply { style = Paint.Style.FILL }

        val footerPaint = Paint().apply {
            color = Color.parseColor("#969696") // 150
            textSize = 8f
            isAntiAlias = true
        }

        var currentPage: PdfDocument.Page? = null

        fun finishCurrentPage() {
            currentPage?.let { page ->
                page.canvas.drawText("Generated by DailyWork Pro - Professionally Managed Workforce", MARGIN, PAGE_HEIGHT - 20f, footerPaint)
                document.finishPage(page)
            }
        }

        fun startNewPage(): Canvas {
            val pageInfo = PdfDocument.PageInfo.Builder(PAGE_WIDTH, PAGE_HEIGHT, pageNumber).create()
            val page = document.startPage(pageInfo)
            currentPage = page
            val canvas = page.canvas

            // Header Section (matches web exactly: pdf.rect(0, 0, pageW, 55, "F"))
            // We scale 55mm to approx 155 points (1mm = 2.83 points)
            val headerHeight = 155f
            canvas.drawRect(0f, 0f, PAGE_WIDTH.toFloat(), headerHeight, paintHeaderBg)

            // Logo Placeholder / Title
            paintTextBold.color = colorHeaderText
            paintTextBold.textSize = 28f
            canvas.drawText("DailyWork Pro", MARGIN, 62f, paintTextBold) // 22mm * 2.83

            // Subtitle
            paintTextNormal.color = colorHeaderSubText
            paintTextNormal.textSize = 12f
            canvas.drawText(data.subtitle, MARGIN, 90f, paintTextNormal) // 32mm * 2.83

            // Worker Info
            paintTextBold.color = colorHeaderWorkerInfoText
            paintTextBold.textSize = 12f
            canvas.drawText("Name: ${data.name}", MARGIN, 124f, paintTextBold) // 44mm * 2.83

            paintTextNormal.color = colorHeaderRoleInfoText
            paintTextNormal.textSize = 10f
            canvas.drawText("Role: ${data.role}", MARGIN, 141f, paintTextNormal) // 50mm * 2.83

            // Month & Contractor Info on Right
            paintTextNormal.color = colorHeaderWorkerInfoText
            paintTextNormal.textSize = 10f
            val rightAlignStart = PAGE_WIDTH - 184f // pageW - 65mm
            canvas.drawText("Month: ${data.monthYearStr}", rightAlignStart, 124f, paintTextNormal)

            paintTextNormal.color = colorHeaderSubText
            canvas.drawText("Contractor: ${data.contractorName}", rightAlignStart, 141f, paintTextNormal)

            yPos = headerHeight + 28f // 65mm * 2.83 ≈ 184f

            return canvas
        }

        var canvas = startNewPage()

        // Financial Summary Title
        paintTextBold.color = colorSummaryTitle
        paintTextBold.textSize = 14f
        canvas.drawText("Monthly Financial Summary", MARGIN, yPos, paintTextBold)
        yPos += 14f // y + 5

        // Stats Table Headers
        val statsHeadBgHeight = 25f
        paintRectFill.color = colorTableHeadBg1
        canvas.drawRect(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos + statsHeadBgHeight, paintRectFill)

        paintTextBold.color = Color.WHITE
        paintTextBold.textSize = 10f
        paintTextBold.textAlign = Paint.Align.CENTER

        val tableWidth = PAGE_WIDTH - (MARGIN * 2)
        val colWidthsStats = floatArrayOf(
            tableWidth * 0.2f, tableWidth * 0.2f, tableWidth * 0.2f, tableWidth * 0.2f, tableWidth * 0.2f
        )
        val statsHeaders = arrayOf("Daily Wage", "Total Man Days", "Gross Earned", "Advance Deducted", "Net Payable")

        var currentX = MARGIN
        for (i in statsHeaders.indices) {
            canvas.drawText(statsHeaders[i], currentX + colWidthsStats[i] / 2f, yPos + 17f, paintTextBold)
            canvas.drawRect(currentX, yPos, currentX + colWidthsStats[i], yPos + statsHeadBgHeight, paintRectBorder)
            currentX += colWidthsStats[i]
        }
        yPos += statsHeadBgHeight

        // Stats Table Body
        val statsBodyHeight = 30f
        paintRectFill.color = Color.WHITE
        canvas.drawRect(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos + statsBodyHeight, paintRectFill)

        paintTextNormal.color = Color.BLACK
        paintTextNormal.textSize = 10f
        paintTextNormal.textAlign = Paint.Align.CENTER

        val finalBalanceFmt = String.format("Rs. %.0f", data.netPayable)
        val statsValues = arrayOf(
            String.format("Rs. %.0f", data.dailyWage),
            String.format("%.1f Days", data.totalManDays),
            String.format("Rs. %.0f", data.grossEarned),
            String.format("Rs. %.0f", data.advanceDeducted),
            finalBalanceFmt
        )

        currentX = MARGIN
        for (i in statsValues.indices) {
            if (i == 4) {
                paintTextBold.color = if (data.netPayable >= 0) colorPositive else colorNegative
                canvas.drawText(statsValues[i], currentX + colWidthsStats[i] / 2f, yPos + 19f, paintTextBold)
            } else {
                canvas.drawText(statsValues[i], currentX + colWidthsStats[i] / 2f, yPos + 19f, paintTextNormal)
            }
            canvas.drawRect(currentX, yPos, currentX + colWidthsStats[i], yPos + statsBodyHeight, paintRectBorder)
            currentX += colWidthsStats[i]
        }
        yPos += statsBodyHeight + 42f // lastAutoTable.finalY + 15mm

        // Detailed Logs Title
        paintTextBold.color = Color.BLACK
        paintTextBold.textAlign = Paint.Align.LEFT
        paintTextBold.textSize = 14f
        canvas.drawText("Detailed Logs", MARGIN, yPos, paintTextBold)
        yPos += 14f // lastAutoTable.finalY + 20mm

        if (data.logs.isEmpty()) {
            paintRectFill.color = Color.WHITE
            val emptyHeight = 40f
            canvas.drawRect(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos + emptyHeight, paintRectFill)
            canvas.drawRect(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos + emptyHeight, paintRectBorder)

            paintTextNormal.color = colorHeaderSubText
            paintTextNormal.textSize = 12f
            paintTextNormal.textAlign = Paint.Align.CENTER
            canvas.drawText("No records available", PAGE_WIDTH / 2f, yPos + 25f, paintTextNormal)
            yPos += emptyHeight
        } else {
            // Logs Table Headers
            val logsHeadBgHeight = 20f
            paintRectFill.color = colorTableHeadBg2
            canvas.drawRect(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos + logsHeadBgHeight, paintRectFill)

            paintTextBold.color = Color.WHITE
            paintTextBold.textSize = 9f
            paintTextBold.textAlign = Paint.Align.CENTER

            val colWidthsLogs = floatArrayOf(
                tableWidth * 0.12f, // Date
                tableWidth * 0.15f, // Status
                tableWidth * 0.18f, // Work Type
                tableWidth * 0.12f, // Daily Wage
                tableWidth * 0.13f, // Overtime
                tableWidth * 0.15f, // Advance
                tableWidth * 0.15f  // Running Balance
            )
            val logsHeaders = arrayOf("Date", "Status", "Work Type", "Daily Wage", "Overtime", "Advance", "Balance")

            currentX = MARGIN
            for (i in logsHeaders.indices) {
                canvas.drawText(logsHeaders[i], currentX + colWidthsLogs[i] / 2f, yPos + 14f, paintTextBold)
                canvas.drawRect(currentX, yPos, currentX + colWidthsLogs[i], yPos + logsHeadBgHeight, paintRectBorder)
                currentX += colWidthsLogs[i]
            }
            yPos += logsHeadBgHeight

            // Logs Table Body
            paintTextNormal.color = Color.BLACK
            paintTextNormal.textSize = 9f
            paintTextNormal.textAlign = Paint.Align.CENTER
            val logRowHeight = 20f

            for ((index, log) in data.logs.withIndex()) {
                if (yPos + logRowHeight > PAGE_HEIGHT - 60f) {
                    finishCurrentPage()
                    pageNumber++
                    canvas = startNewPage()

                    // Redraw table headers on new page
                    paintRectFill.color = colorTableHeadBg2
                    canvas.drawRect(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos + logsHeadBgHeight, paintRectFill)
                    paintTextBold.color = Color.WHITE
                    currentX = MARGIN
                    for (i in logsHeaders.indices) {
                        canvas.drawText(logsHeaders[i], currentX + colWidthsLogs[i] / 2f, yPos + 14f, paintTextBold)
                        canvas.drawRect(currentX, yPos, currentX + colWidthsLogs[i], yPos + logsHeadBgHeight, paintRectBorder)
                        currentX += colWidthsLogs[i]
                    }
                    yPos += logsHeadBgHeight
                }

                paintRectFill.color = if (index % 2 == 0) Color.WHITE else colorStripedRow
                canvas.drawRect(MARGIN, yPos, PAGE_WIDTH - MARGIN, yPos + logRowHeight, paintRectFill)

                val logValues = arrayOf(log.date, log.status, log.workType, log.dailyWage, log.overtime, log.advanceAmount, log.runningBalance)
                currentX = MARGIN
                for (i in logValues.indices) {
                    canvas.drawText(logValues[i], currentX + colWidthsLogs[i] / 2f, yPos + 14f, paintTextNormal)
                    canvas.drawRect(currentX, yPos, currentX + colWidthsLogs[i], yPos + logRowHeight, paintRectBorder)
                    currentX += colWidthsLogs[i]
                }
                yPos += logRowHeight
            }
        }

        finishCurrentPage()

        return saveDocument(context, document, data)
    }

    private fun saveDocument(context: Context, document: PdfDocument, data: PdfData): File? {
        val fileName = "passbook_${data.userId}_${data.yearNumericStr}-${data.monthNumericStr}.pdf"
        val cachePath = File(context.cacheDir, "docs")
        cachePath.mkdirs()
        val file = File(cachePath, fileName)

        return try {
            val fos = FileOutputStream(file)
            document.writeTo(fos)
            document.close()
            fos.close()
            file
        } catch (e: Exception) {
            e.printStackTrace()
            document.close()
            null
        }
    }
}
